name: markdown-lint
author: Articulate Global, LLC
description: Lint your markdown
inputs:
  version:
    description: Version of markdownlint-cli to use
    required: false
  config:
    description: markdownlint config file
    required: false
  files:
    description: Markdown files to scan
    required: false
    default: '**/*.{md,markdown}'
  ignore:
    description: Files or directories to ignore
    required: false
  fix:
    description: Try to fix basic errors
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  color: blue
  icon: check-circle
