name: markdown-lint
author: Articulate Global, LLC
description: Lint your markdown files.
inputs:
  version:
    description: Version of markdownlint-cli to use.
    required: false
  config:
    description: markdownlint config file.
    required: false
  files:
    description: Markdown files to scan.
    required: false
    default: '**/*.{md,markdown}'
  ignore:
    description: File or directory to ignore. If ignoring more than one file/directory you must use `.markdownlintignore` instead.
    required: false
  fix:
    description: Try to fix basic errors.
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  color: blue
  icon: check-circle
